# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Development
  displayName: Development
  jobs:
  - job: myJob
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Hello world"
  - deployment: runcontainer
    displayName: Run Container
    workspace:
      clean: all
    environment:
      name: Development
      resourceType: VirtualMachine
      tags: web
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: echo "Hello world"